name: Update Weather Rankings Data

on:
  #schedule:
  # - cron: '*/15 * * * *' # Run every 15 minutes
  workflow_dispatch: # Allow manual triggering
  repository_dispatch:
    types: [manual-trigger] # Allows external triggers (e.g., Cron-Job.org)

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows write access to repository files
      actions: read # Allows reading actions logs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas urllib3 duckdb boto3 google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
      
      - name: Set up Google Drive credentials
        run: |
          echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}' > google_credentials.json
        
      - name: Run scraper
        env:
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
        run: python scraper.py
        
      - name: Clean up credentials
        if: always()
        run: |
          rm -f google_credentials.json
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data.json consolidated_rankings.csv
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update weather rankings data"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
          fi
