name: Update Hottest Place Data

on:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes
  workflow_dispatch:  # Allow manual triggering
  repository_dispatch:
    types: [manual-trigger]  # Allows external triggers (e.g., Cron-Job.org)

jobs:
  update-data:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows write access to repository files
      actions: read  # Allows reading actions logs

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Updated to latest version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to latest version
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python scraper.py

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add data.json
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update hottest place data"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        fi
